In [4]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yasserh/titanic-dataset")

print("Path to dataset files:", path)

Using Colab cache for faster access to the 'titanic-dataset' dataset.
Path to dataset files: /kaggle/input/titanic-dataset

In [5]:
import pandas as pd
import os

# Correcting the dataset file name based on the directory listing
dataset_file_path = f"{path}/Titanic-Dataset.csv"

# Check if the file exists before attempting to read it
if not os.path.exists(dataset_file_path):
    print(f"File not found: {dataset_file_path}. Listing contents of {path}:")
    print(os.listdir(path))
else:
    df = pd.read_csv(dataset_file_path)

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [7]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [8]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
import numpy as np

# 1. Handle missing values
# Fill missing 'Age' values with the median
df['Age'].fillna(df['Age'].median(), inplace=True)
print("Missing 'Age' values filled with median.")

Missing 'Age' values filled with median.

/tmp/ipykernel_2006/794771251.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].median(), inplace=True)

In [10]:
print(df['Age'])

0      22.0
1      38.0
2      26.0
3      35.0
4      35.0
       ...
886    27.0
887    19.0
888    28.0
889    26.0
890    32.0
Name: Age, Length: 891, dtype: float64

In [11]:

# Fill missing 'Embarked' values with the mode (most frequent value)
# .mode()[0] handles cases where there might be multiple modes
df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)
print("Missing 'Embarked' values filled with mode.")

Missing 'Embarked' values filled with mode.

/tmp/ipykernel_2006/1163394761.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Embarked'].fillna(df['Embarked'].mode()[0], inplace=True)

In [12]:
print(df['Embarked'])

0      S
1      C
2      S
3      S
4      S
      ..
886    S
887    S
888    S
889    C
890    Q
Name: Embarked, Length: 891, dtype: object

In [13]:
# Drop 'Cabin' column due to a large number of missing values
df.drop('Cabin', axis=1, inplace=True)
print("'Cabin' column dropped due to many missing values.")

'Cabin' column dropped due to many missing values.

In [15]:
# Verify no more missing values in these columns
print("\nMissing values after handling:")
print(df[['Age', 'Embarked']].isnull().sum())

Missing values after handling:
Age         0
Embarked    0
dtype: int64

In [18]:
df['Age'].dtype

dtype('float64')

In [19]:
# 3. Remove duplicates
df.drop_duplicates(inplace=True)
print(f"\nDuplicates removed. DataFrame shape after removing duplicates: {df.shape}")

Duplicates removed. DataFrame shape after removing duplicates: (891, 11)

In [20]:
# Display the first few rows and info after these operations
print("\nDataFrame head after handling missing values and duplicates:")
print(df.head())

DataFrame head after handling missing values and duplicates:
   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0

   Parch            Ticket     Fare Embarked
0      0         A/5 21171   7.2500        S
1      0          PC 17599  71.2833        C
2      0  STON/O2. 3101282   7.9250        S
3      0            113803  53.1000        S
4      0            373450   8.0500        S

In [21]:
print("\nDataFrame info after handling missing values and duplicates:")
df.info()

DataFrame info after handling missing values and duplicates:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
dtypes: float64(2), int64(5), object(4)
memory usage: 76.7+ KB

In [22]:
# 4. Create 2 new derived columns
# FamilySize: Sum of SibSp and Parch, plus 1 for the passenger themselves
df['FamilySize'] = df['SibSp'] + df['Parch'] + 1
print("Created 'FamilySize' column.")

# IsAlone: 1 if FamilySize is 1, 0 otherwise
df['IsAlone'] = np.where(df['FamilySize'] == 1, 1, 0)
print("Created 'IsAlone' column.")

# Display new columns
print("\nDataFrame head with new columns:")
print(df[['FamilySize', 'IsAlone']].head())

Created 'FamilySize' column.
Created 'IsAlone' column.

DataFrame head with new columns:
   FamilySize  IsAlone
0           2        0
1           2        0
2           1        1
3           2        0
4           1        1

In [23]:
# 5. Reshape the data using .groupby() + .agg() to produce a summary table
# Summarize survival rate, average age, and average fare by Pclass and Sex
summary_table = df.groupby(['Pclass', 'Sex']).agg(
    SurvivalRate=('Survived', 'mean'),
    AverageAge=('Age', 'mean'),
    AverageFare=('Fare', 'mean'),
    TotalPassengers=('PassengerId', 'count')
).reset_index()

print("\nSummary table (Survival rate, avg age, avg fare by Pclass and Sex):")
print(summary_table)

Summary table (Survival rate, avg age, avg fare by Pclass and Sex):
   Pclass     Sex  SurvivalRate  AverageAge  AverageFare  TotalPassengers
0       1  female      0.968085   33.978723   106.125798               94
1       1    male      0.368852   38.995246    67.226127              122
2       2  female      0.921053   28.703947    21.970121               76
3       2    male      0.157407   30.512315    19.741782              108
4       3  female      0.500000   23.572917    16.118810              144
5       3    male      0.135447   26.911873    12.661633              347

In [24]:
# 6. Merge with a second small manually created DataFrame to add extra context
# Create a DataFrame to map Pclass to a more descriptive label
pclass_labels = pd.DataFrame({
    'Pclass': [1, 2, 3],
    'ClassDescription': ['First Class', 'Second Class', 'Third Class']
})

# Merge the summary table with the Pclass labels
summary_with_context = pd.merge(summary_table, pclass_labels, on='Pclass', how='left')

print("\nSummary table after merging with Class Description:")
print(summary_with_context)

# Display overall info after all operations
print("\nFinal DataFrame info after all operations:")
df.info()

Summary table after merging with Class Description:
   Pclass     Sex  SurvivalRate  AverageAge  AverageFare  TotalPassengers  \
0       1  female      0.968085   33.978723   106.125798               94
1       1    male      0.368852   38.995246    67.226127              122
2       2  female      0.921053   28.703947    21.970121               76
3       2    male      0.157407   30.512315    19.741782              108
4       3  female      0.500000   23.572917    16.118810              144
5       3    male      0.135447   26.911873    12.661633              347

  ClassDescription
0      First Class
1      First Class
2     Second Class
3     Second Class
4      Third Class
5      Third Class

Final DataFrame info after all operations:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Embarked     891 non-null    object
 11  FamilySize   891 non-null    int64
 12  IsAlone      891 non-null    int64
dtypes: float64(2), int64(7), object(4)
memory usage: 90.6+ KB