In [1]:
import pandas as pd
import numpy as np

In [2]:
players = pd.read_csv('/content/afl_players_info_raw.csv')

In [48]:
stats = pd.read_csv('/content/afl_players_seasonal_stats_raw.csv')

/tmp/ipykernel_1813/1411203859.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  stats = pd.read_csv('/content/afl_players_seasonal_stats_raw.csv')

In [4]:
players.head()

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,height,weight,profile_pic,player_link,player_common_names,player_teams
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,200,100,NaN,https://afltables.com/afl/stats/players/R/Ryan...,NaN,"{Geelong Cats,St Kilda Saints}"
1,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,182,87,NaN,https://afltables.com/afl/stats/players/G/Gary...,NaN,"{Geelong Cats,Gold Coast Suns}"
2,43276,Leek Aleer,Leek_Aleer,Leek,Aleer,2001-08-21,2022-07-30,20,2025-09-06,24,195,85,https://res.cloudinary.com/dijzdikkh/image/upl...,https://afltables.com/afl/stats/players/L/Leek...,NaN,NaN
3,43264,Nathan Ablett,Nathan_Ablett,Nathan,Ablett,1985-12-13,2005-08-12,19,2011-08-28,25,195,95,NaN,https://afltables.com/afl/stats/players/N/Nath...,NaN,"{Geelong Cats,Gold Coast Suns}"
4,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,196,101,NaN,https://afltables.com/afl/stats/players/C/Cain...,NaN,"{Carlton Blues,Port Adelaide Power,St Kilda Sa..."

In [49]:
stats.head()

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN

In [6]:
players.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2848 entries, 0 to 2847
Data columns (total 16 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   2848 non-null   int64
 1   player_name          2848 non-null   object
 2   player_full_name     2848 non-null   object
 3   first_name           2848 non-null   object
 4   last_name            2848 non-null   object
 5   born_date            2848 non-null   object
 6   debut_date           2848 non-null   object
 7   debut_age            2848 non-null   int64
 8   last_date            2848 non-null   object
 9   last_age             2848 non-null   int64
 10  height               2848 non-null   int64
 11  weight               2848 non-null   int64
 12  profile_pic          637 non-null    object
 13  player_link          2848 non-null   object
 14  player_common_names  75 non-null     object
 15  player_teams         2754 non-null   object
dtypes: int64(5), object(11)
memory usage: 356.1+ KB

In [50]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  object
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  object
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(4), object(2)
memory usage: 10.3+ MB

In [8]:
players.describe()

                 id    debut_age     last_age       height       weight
count   2848.000000  2848.000000  2848.000000  2848.000000  2848.000000
mean   44858.623947    19.595857    25.765449   187.344803    86.012289
std      912.449281     1.824956     4.339853     7.318328     8.923524
min    43260.000000    16.000000    18.000000   163.000000     0.000000
25%    44063.750000    18.000000    22.000000   182.000000    80.000000
50%    44885.500000    19.000000    25.000000   187.000000    85.000000
75%    45662.250000    20.000000    29.000000   192.000000    92.000000
max    46374.000000    29.000000    40.000000   211.000000   118.000000

In [51]:
stats.describe()

,year,games_played,kicks,marks,handballs,disposals,goals,behinds,hit_outs,tackles,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
count,25491.000000,25491.000000,25439.000000,25306.000000,25378.000000,25467.000000,22954.000000,22802.000000,19785.000000,24980.000000,...,22155.000000,22169.000000,20566.000000,20326.000000,21848.000000,19837.000000,18399.000000,25491.000000,25491.000000,19245.000000
mean,2010.194500,10.748617,98.697001,42.882281,67.689652,166.041583,7.169208,5.131524,21.316250,26.029944,...,5.429564,8.575497,0.683696,0.732692,2.102938,0.665075,0.481434,3.591742,59.519850,77.742931
std,9.342562,7.832753,92.259369,39.119496,68.603571,154.153533,10.744221,6.806970,80.547687,26.819368,...,2.585986,3.994015,0.672074,0.821606,1.629118,0.893630,0.487706,4.326204,21.492939,14.190194
min,1983.000000,-21.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-6.000000,0.000000
25%,2003.000000,3.000000,20.000000,9.000000,13.000000,34.000000,1.000000,1.000000,0.000000,6.000000,...,3.800000,5.600000,0.100000,0.000000,1.000000,0.000000,0.000000,0.400000,45.000000,72.500000
50%,2011.000000,10.000000,66.000000,31.000000,44.000000,114.000000,3.000000,3.000000,0.000000,17.000000,...,5.000000,8.000000,0.500000,0.500000,1.700000,0.300000,0.300000,2.300000,58.700000,80.400000
75%,2018.000000,19.000000,161.000000,70.000000,103.000000,268.000000,9.000000,7.000000,4.000000,38.000000,...,6.600000,11.100000,1.000000,1.000000,2.600000,1.000000,0.800000,5.200000,73.800000,86.300000
max,2025.000000,23.000000,512.000000,226.000000,482.000000,787.000000,123.000000,84.000000,1007.000000,205.000000,...,22.000000,29.000000,6.000000,8.000000,22.000000,13.000000,4.000000,59.000000,149.000000,100.000000

In [10]:
players.shape

(2848, 16)

In [52]:
stats.shape

(25491, 54)

In [12]:
players.isnull().sum()

id                        0
player_name               0
player_full_name          0
first_name                0
last_name                 0
born_date                 0
debut_date                0
debut_age                 0
last_date                 0
last_age                  0
height                    0
weight                    0
profile_pic            2211
player_link               0
player_common_names    2773
player_teams             94
dtype: int64

In [53]:
stats.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

In [14]:
# Drop columns with excessive missing values
players = players.drop(columns=['profile_pic', 'player_common_names'])

In [15]:
# Handle missing values in player_teams by filling with 'Unknown'
players['player_teams'] = players['player_teams'].fillna('Unknown')

In [16]:
# Verify the cleaning
print(players.isnull().sum())

id                  0
player_name         0
player_full_name    0
first_name          0
last_name           0
born_date           0
debut_date          0
debut_age           0
last_date           0
last_age            0
height              0
weight              0
player_link         0
player_teams        0
dtype: int64

In [17]:
from google.colab import files

# Save the cleaned DataFrame to a CSV file
players.to_csv('cleaned_afl_players_info_raw.csv', index=False)

# Trigger the download to the local machine
files.download('cleaned_afl_players_info_raw.csv')

In [54]:
stats.duplicated().sum()

np.int64(10)

In [55]:
stats.drop_duplicates()

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,Geelong Cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,Geelong Cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,Geelong Cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,St Kilda Saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,Geelong Cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25486,ID_43738,2013,Greater Western Sydney Giants,False,1,3.0,1.0,1.0,4.0,0.0,...,2.0,1.0,0.0,0.0,3.0,0.0,0.0,0.0,30.0,85.0
25487,ID_43660,2015,Carlton Blues,False,22,216.0,75.0,262.0,478.0,0.0,...,8.4,13.2,0.3,0.0,1.2,0.2,0.2,0.1,79.6,90.5
25488,ID_46153,2025,Melbourne Demons,False,5,15.0,5.0,12.0,27.0,3.0,...,3.4,1.8,0.4,0.8,2.8,0.0,0.4,4.2,30.8,62.4
25489,ID_44965,2005,Fremantle Dockers,False,6,30.0,11.0,41.0,71.0,1.0,...,4.8,7.2,0.0,0.2,1.8,0.2,0.0,1.3,41.5,47.8
25490,ID_45608,1998,carlton blues,False,15,117.0,24.0,97.0,214.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.7,47.4,NaN

In [56]:
stats[stats["games_played"] == 0].shape

(0, 54)

In [57]:
# Remove 'ID_' prefix if it exists and convert to integer
stats['player_id'] = stats['player_id'].astype(str).str.replace('ID_', '')
stats['player_id'] = pd.to_numeric(stats['player_id'], errors='coerce').astype(int)

In [58]:
stats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25491 entries, 0 to 25490
Data columns (total 54 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   player_id                    25491 non-null  int64
 1   year                         25491 non-null  int64
 2   team                         25491 non-null  object
 3   is_finals                    25491 non-null  bool
 4   games_played                 25491 non-null  int64
 5   kicks                        25439 non-null  float64
 6   marks                        25306 non-null  float64
 7   handballs                    25378 non-null  float64
 8   disposals                    25467 non-null  float64
 9   goals                        22954 non-null  float64
 10  behinds                      22802 non-null  float64
 11  hit_outs                     19785 non-null  float64
 12  tackles                      24980 non-null  float64
 13  rebound_50s                  21958 non-null  float64
 14  inside_50s                   22520 non-null  float64
 15  clearances                   22056 non-null  float64
 16  clangers                     22553 non-null  float64
 17  free_kicks_for               24418 non-null  float64
 18  free_kicks_against           24513 non-null  float64
 19  brownlow_votes               18494 non-null  float64
 20  contested_possessions        22155 non-null  float64
 21  uncontested_possessions      22169 non-null  float64
 22  contested_marks              20566 non-null  float64
 23  marks_inside_50              20326 non-null  float64
 24  one_percenters               21848 non-null  float64
 25  bounces                      19837 non-null  float64
 26  goal_assists                 18399 non-null  float64
 27  total_score                  25491 non-null  int64
 28  total_fantasy_points         25491 non-null  int64
 29  total_percentage_played      19245 non-null  float64
 30  avg_kicks                    25439 non-null  float64
 31  avg_marks                    25306 non-null  float64
 32  avg_handballs                25378 non-null  float64
 33  avg_disposals                25467 non-null  float64
 34  avg_goals                    22954 non-null  float64
 35  avg_behinds                  22802 non-null  float64
 36  avg_hit_outs                 19785 non-null  float64
 37  avg_tackles                  24980 non-null  float64
 38  avg_rebound_50s              21958 non-null  float64
 39  avg_inside_50s               22520 non-null  float64
 40  avg_clearances               22056 non-null  float64
 41  avg_clangers                 22553 non-null  float64
 42  avg_free_kicks_for           24418 non-null  float64
 43  avg_free_kicks_against       24513 non-null  float64
 44  avg_contested_possessions    22155 non-null  float64
 45  avg_uncontested_possessions  22169 non-null  float64
 46  avg_contested_marks          20566 non-null  float64
 47  avg_marks_inside_50          20326 non-null  float64
 48  avg_one_percenters           21848 non-null  float64
 49  avg_bounces                  19837 non-null  float64
 50  avg_goal_assists             18399 non-null  float64
 51  avg_score                    25491 non-null  float64
 52  avg_fantasy_points           25491 non-null  float64
 53  avg_percentage_played        19245 non-null  float64
dtypes: bool(1), float64(47), int64(5), object(1)
memory usage: 10.3+ MB

In [59]:
stats.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                            52
marks                           185
handballs                       113
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

#Kicks Column Missing Values fixed with median

In [60]:
stats['kicks'] = stats['kicks'].fillna(stats['kicks'].median())

In [61]:
stats['kicks'].isnull().sum()

np.int64(0)

#Marks Column Missing Values Fixed by Using Median

In [62]:
stats['marks'] = stats['marks'].fillna(stats['marks'].median())

In [63]:
stats['marks'].isnull().sum()

np.int64(0)

Again Replacing Hnadballs Column with Median Because Mean is higher and it will then effect the average.

In [64]:
stats['handballs'] = stats['handballs'].fillna(stats['handballs'].median())

In [65]:
stats['handballs'].isnull().sum()

np.int64(0)

In [66]:
stats.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                             0
marks                             0
handballs                         0
disposals                        24
goals                          2537
behinds                        2689
hit_outs                       5706
tackles                         511
rebound_50s                    3533
inside_50s                     2971
clearances                     3435
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

#Remaining columns are also replaced by median as mean is not optimal because of outliers in the dataset
so replacing the values of other columns left collectively in on cell

In [67]:
# 1. Filling missing values for common stats using median
columns_to_fix = ['disposals', 'goals', 'behinds', 'tackles', 'hit_outs', 'inside_50s', 'clearances']
for col in columns_to_fix:
    stats[col] = stats[col].fillna(stats[col].median())

In [68]:
stats.isnull().sum()

player_id                         0
year                              0
team                              0
is_finals                         0
games_played                      0
kicks                             0
marks                             0
handballs                         0
disposals                         0
goals                             0
behinds                           0
hit_outs                          0
tackles                           0
rebound_50s                    3533
inside_50s                        0
clearances                        0
clangers                       2938
free_kicks_for                 1073
free_kicks_against              978
brownlow_votes                 6997
contested_possessions          3336
uncontested_possessions        3322
contested_marks                4925
marks_inside_50                5165
one_percenters                 3643
bounces                        5654
goal_assists                   7092
total_score                       0
total_fantasy_points              0
total_percentage_played        6246
avg_kicks                        52
avg_marks                       185
avg_handballs                   113
avg_disposals                    24
avg_goals                      2537
avg_behinds                    2689
avg_hit_outs                   5706
avg_tackles                     511
avg_rebound_50s                3533
avg_inside_50s                 2971
avg_clearances                 3435
avg_clangers                   2938
avg_free_kicks_for             1073
avg_free_kicks_against          978
avg_contested_possessions      3336
avg_uncontested_possessions    3322
avg_contested_marks            4925
avg_marks_inside_50            5165
avg_one_percenters             3643
avg_bounces                    5654
avg_goal_assists               7092
avg_score                         0
avg_fantasy_points                0
avg_percentage_played          6246
dtype: int64

We can now check the unique list of teams to ensure they are consistent.

In [69]:
print("Unique Teams:")
print(sorted(stats['team'].unique()))

Unique Teams:
[' ADELAIDE CROWS ', ' Adelaide Crows ', ' BRISBANE LIONS ', ' Brisbane Lions ', ' CARLTON BLUES ', ' COLLINGWOOD MAGPIES ', ' Carlton Blues ', ' Collingwood Magpies ', ' ESSENDON BOMBERS ', ' Essendon Bombers ', ' FREMANTLE DOCKERS ', ' Fitzroy Lions ', ' Fremantle Dockers ', ' GOLD COAST SUNS ', ' GREATER WESTERN SYDNEY GIANTS ', ' Geelong Cats ', ' Gold Coast Suns ', ' Greater Western Sydney Giants ', ' HAWTHORN HAWKS ', ' Hawthorn Hawks ', ' Melbourne Demons ', ' NORTH MELBOURNE KANGAROOS ', ' North Melbourne Kangaroos ', ' PORT ADELAIDE POWER ', ' Port Adelaide Power ', ' RICHMOND TIGERS ', ' Richmond Tigers ', ' ST KILDA SAINTS ', ' SYDNEY SWANS ', ' St Kilda Saints ', ' Sydney Swans ', ' WEST COAST EAGLES ', ' WESTERN BULLDOGS ', ' West Coast Eagles ', ' Western Bulldogs ', ' adelaide crows ', ' brisbane bears ', ' brisbane lions ', ' carlton blues ', ' collingwood magpies ', ' essendon bombers ', ' fremantle dockers ', ' geelong cats ', ' gold coast suns ', ' greater western sydney giants ', ' hawthorn hawks ', ' melbourne demons ', ' north melbourne kangaroos ', ' port adelaide power ', ' richmond tigers ', ' st kilda saints ', ' sydney swans ', ' west coast eagles ', ' western bulldogs ', 'ADELAIDE CROWS', 'Adelaide Crows', 'BRISBANE BEARS', 'BRISBANE LIONS', 'Brisbane Bears', 'Brisbane Lions', 'CARLTON BLUES', 'COLLINGWOOD MAGPIES', 'Carlton Blues', 'Collingwood Magpies', 'ESSENDON BOMBERS', 'Essendon Bombers', 'FITZROY LIONS', 'FREMANTLE DOCKERS', 'Fitzroy Lions', 'Fremantle Dockers', 'GEELONG CATS', 'GOLD COAST SUNS', 'GREATER WESTERN SYDNEY GIANTS', 'Geelong Cats', 'Gold Coast Suns', 'Greater Western Sydney Giants', 'HAWTHORN HAWKS', 'Hawthorn Hawks', 'MELBOURNE DEMONS', 'Melbourne Demons', 'NORTH MELBOURNE KANGAROOS', 'North Melbourne Kangaroos', 'PORT ADELAIDE POWER', 'Port Adelaide Power', 'RICHMOND TIGERS', 'Richmond Tigers', 'ST KILDA SAINTS', 'SYDNEY SWANS', 'St Kilda Saints', 'Sydney Swans', 'WEST COAST EAGLES', 'WESTERN BULLDOGS', 'West Coast Eagles', 'Western Bulldogs', 'adelaide crows', 'brisbane bears', 'brisbane lions', 'carlton blues', 'collingwood magpies', 'essendon bombers', 'fitzroy lions', 'fremantle dockers', 'geelong cats', 'gold coast suns', 'greater western sydney giants', 'hawthorn hawks', 'melbourne demons', 'north melbourne kangaroos', 'port adelaide power', 'richmond tigers', 'st kilda saints', 'sydney swans', 'west coast eagles', 'western bulldogs']

In [70]:
# Convert team names to lowercase and strip whitespace
stats['team'] = stats['team'].str.lower().str.strip()

# Again Verify the unique list of team names
print("Cleaned Unique Teams:")
print(sorted(stats['team'].unique()))

Cleaned Unique Teams:
['adelaide crows', 'brisbane bears', 'brisbane lions', 'carlton blues', 'collingwood magpies', 'essendon bombers', 'fitzroy lions', 'fremantle dockers', 'geelong cats', 'gold coast suns', 'greater western sydney giants', 'hawthorn hawks', 'melbourne demons', 'north melbourne kangaroos', 'port adelaide power', 'richmond tigers', 'st kilda saints', 'sydney swans', 'west coast eagles', 'western bulldogs']

In [71]:
#Handle 'disposals' specifically as it is a sum of kicks + handballs
stats['disposals'] = stats['kicks'] + stats['handballs']

In [72]:
# Verify results
print("Missing values after cleaning core columns:")
print(stats[columns_to_fix].isnull().sum())
display(stats.head())

Missing values after cleaning core columns:
disposals     0
goals         0
behinds       0
tackles       0
hit_outs      0
inside_50s    0
clearances    0
dtype: int64

,player_id,year,team,is_finals,games_played,kicks,marks,handballs,disposals,goals,...,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_marks_inside_50,avg_one_percenters,avg_bounces,avg_goal_assists,avg_score,avg_fantasy_points,avg_percentage_played
0,43261,2018,geelong cats,False,3,17.0,9.0,21.0,38.0,3.0,...,6.7,6.7,0.3,1.7,4.3,0.0,0.3,6.7,92.7,84.3
1,43261,2018,geelong cats,True,1,3.0,2.0,2.0,5.0,0.0,...,2.0,3.0,1.0,1.0,5.0,0.0,0.0,1.0,61.0,81.0
2,43261,2019,geelong cats,False,1,5.0,3.0,6.0,11.0,1.0,...,6.0,8.0,0.0,1.0,3.0,0.0,0.0,6.0,74.0,83.0
3,43261,2020,st kilda saints,False,1,2.0,2.0,1.0,3.0,1.0,...,0.0,3.0,0.0,1.0,0.0,0.0,0.0,6.0,22.0,54.0
4,43262,2002,geelong cats,False,12,37.0,13.0,63.0,100.0,10.0,...,5.7,3.0,0.3,0.3,1.0,0.2,0.0,5.3,36.9,NaN

In [73]:
# Identify columns with 5000 or more missing values
null_counts = stats.isnull().sum()
columns_to_drop_5000 = null_counts[null_counts >= 5000].index.tolist()

print(f"Dropping columns with >= 5000 missing values: {columns_to_drop_5000}")

# Drop the identified columns
stats = stats.drop(columns=columns_to_drop_5000)

Dropping columns with >= 5000 missing values: ['brownlow_votes', 'marks_inside_50', 'bounces', 'goal_assists', 'total_percentage_played', 'avg_hit_outs', 'avg_marks_inside_50', 'avg_bounces', 'avg_goal_assists', 'avg_percentage_played']

#filling the remaining columns with median values as well

In [78]:
numeric_columns = stats.select_dtypes(include=["float64", "int64"]).columns

stats[numeric_columns] = stats[numeric_columns].fillna(
    stats[numeric_columns].median()
)

In [79]:
stats.isnull().sum()

player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
one_percenters                 0
total_score                    0
total_fantasy_points           0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_one_percenters             0
avg_score                      0
avg_fantasy_points             0
dtype: int64

In [80]:
stats.shape

(25491, 44)

In [81]:
stats.to_csv("cleaned_seasonal_stats.csv", index=False)

In [82]:
from google.colab import files
files.download('cleaned_seasonal_stats.csv')

#merging the datasets
players dataset id is unique and stats dataset has player_id so we use these 2 to merge and we use inner merge for this.

In [83]:
merged = pd.merge(
    players,
    stats,
    left_on="id",
    right_on="player_id",
    how="inner"
)

In [84]:
merged.to_csv("merged_players.csv", index=False)

In [85]:
from google.colab import files
files.download('merged_players.csv')

#Validation Report
1st we check  shape of all three
2nd we check null values
3rd duplicate check
4th players with unmatched seasonal stats id
5th season stats with no match of id

In [86]:
print("Players:", players.shape)

print("Season Stats:", stats.shape)

print("Merged:", merged.shape)

Players: (2848, 14)
Season Stats: (25491, 44)
Merged: (25145, 58)

In [88]:
players.isnull().sum()

id                  0
player_name         0
player_full_name    0
first_name          0
last_name           0
born_date           0
debut_date          0
debut_age           0
last_date           0
last_age            0
height              0
weight              0
player_link         0
player_teams        0
dtype: int64

In [89]:
stats.isnull().sum()

player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
one_percenters                 0
total_score                    0
total_fantasy_points           0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_one_percenters             0
avg_score                      0
avg_fantasy_points             0
dtype: int64

In [90]:
merged.isnull().sum()

id                             0
player_name                    0
player_full_name               0
first_name                     0
last_name                      0
born_date                      0
debut_date                     0
debut_age                      0
last_date                      0
last_age                       0
height                         0
weight                         0
player_link                    0
player_teams                   0
player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
one_percenters                 0
total_score                    0
total_fantasy_points           0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_one_percenters             0
avg_score                      0
avg_fantasy_points             0
dtype: int64

In [91]:
print("Players:", players.duplicated().sum())

print("Stats:", stats.duplicated().sum())

print("Merged:", merged.duplicated().sum())

Players: 5
Stats: 10
Merged: 64

In [96]:
players = players.drop_duplicates()
stats = stats.drop_duplicates()

In [97]:
print(players.duplicated().sum())
print(stats.duplicated().sum())

0
0

In [100]:
merged[merged.duplicated(keep=False)]

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,...,avg_clearances,avg_clangers,avg_free_kicks_for,avg_free_kicks_against,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_one_percenters,avg_score,avg_fantasy_points
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,2.7,3.3,0.7,2.0,6.7,6.7,0.3,4.3,6.7,92.7
1,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,3.0,0.0,2.0,2.0,3.0,1.0,5.0,1.0,61.0
2,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,3.0,4.0,1.0,3.0,6.0,8.0,0.0,3.0,6.0,74.0
3,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,6.0,22.0
4,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,2.7,3.3,0.7,2.0,6.7,6.7,0.3,4.3,6.7,92.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
312,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,...,2.6,2.6,1.6,1.2,5.2,5.9,0.4,1.6,3.7,57.7
313,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,...,3.0,1.5,2.5,1.0,4.5,2.5,0.5,2.0,0.0,44.5
314,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,...,1.4,1.5,1.2,0.8,3.7,4.8,0.4,1.6,2.1,46.3
315,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,...,2.1,2.0,1.5,1.1,4.5,4.9,0.3,1.6,1.3,51.0
316,43265,Cain Ackland,Cain_Ackland,Cain,Ackland,1982-03-16,2001-03-30,19,2008-05-16,26,...,1.0,2.0,0.0,0.0,3.0,8.0,0.0,0.0,0.0,54.0

In [101]:
merged = merged.drop_duplicates()

In [102]:
print("Players:", players.duplicated().sum())

print("Stats:", stats.duplicated().sum())

print("Merged:", merged.duplicated().sum())

Players: 0
Stats: 0
Merged: 0

In [103]:
unmatched_players = players[
    ~players["id"].isin(stats["player_id"])
]

print(unmatched_players.shape)

(0, 14)

In [104]:
unmatched_stats = stats[
    ~stats["player_id"].isin(players["id"])
]

print(unmatched_stats.shape)

(400, 44)

In [105]:
merged.head()

,id,player_name,player_full_name,first_name,last_name,born_date,debut_date,debut_age,last_date,last_age,...,avg_clearances,avg_clangers,avg_free_kicks_for,avg_free_kicks_against,avg_contested_possessions,avg_uncontested_possessions,avg_contested_marks,avg_one_percenters,avg_score,avg_fantasy_points
0,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,2.7,3.3,0.7,2.0,6.7,6.7,0.3,4.3,6.7,92.7
1,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,3.0,0.0,2.0,2.0,3.0,1.0,5.0,1.0,61.0
2,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,3.0,4.0,1.0,3.0,6.0,8.0,0.0,3.0,6.0,74.0
3,43261,Ryan Abbott,Ryan_Abbott,Ryan,Abbott,1991-06-25,2018-08-02,27,2020-09-05,29,...,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,6.0,22.0
8,43262,Gary Ablett,Gary_Ablett1,Gary,Ablett,1984-05-14,2002-03-30,17,2020-10-24,36,...,1.1,0.9,0.6,0.1,5.7,3.0,0.3,1.0,5.3,36.9

## Validation Report Overview

### 1. Row Counts Before and After Cleaning/Merging

In [106]:
# Original shapes (based on initial data loading and info checks)
print(f"Original Players DataFrame Shape: (2848, 16)")
print(f"Original Season Stats DataFrame Shape: (25491, 54)")

# Current shapes after cleaning and merging
print("\nShape after cleaning and merging:")
print(f"Players DataFrame after deduplication: {players.shape}")
print(f"Season Stats DataFrame after deduplication: {stats.shape}")
print(f"Merged DataFrame after deduplication: {merged.shape}")

Original Players DataFrame Shape: (2848, 16)
Original Season Stats DataFrame Shape: (25491, 54)

Shape after cleaning and merging:
Players DataFrame after deduplication: (2843, 14)
Season Stats DataFrame after deduplication: (25481, 44)
Merged DataFrame after deduplication: (25081, 58)

### 2. Missing Values Handled

In [107]:
print("Missing values in Players DataFrame after cleaning:")
print(players.isnull().sum())

print("\nMissing values in Season Stats DataFrame after cleaning:")
print(stats.isnull().sum())

print("\nMissing values in Merged DataFrame:")
print(merged.isnull().sum())

Missing values in Players DataFrame after cleaning:
id                  0
player_name         0
player_full_name    0
first_name          0
last_name           0
born_date           0
debut_date          0
debut_age           0
last_date           0
last_age            0
height              0
weight              0
player_link         0
player_teams        0
dtype: int64

Missing values in Season Stats DataFrame after cleaning:
player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
one_percenters                 0
total_score                    0
total_fantasy_points           0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_one_percenters             0
avg_score                      0
avg_fantasy_points             0
dtype: int64

Missing values in Merged DataFrame:
id                             0
player_name                    0
player_full_name               0
first_name                     0
last_name                      0
born_date                      0
debut_date                     0
debut_age                      0
last_date                      0
last_age                       0
height                         0
weight                         0
player_link                    0
player_teams                   0
player_id                      0
year                           0
team                           0
is_finals                      0
games_played                   0
kicks                          0
marks                          0
handballs                      0
disposals                      0
goals                          0
behinds                        0
hit_outs                       0
tackles                        0
rebound_50s                    0
inside_50s                     0
clearances                     0
clangers                       0
free_kicks_for                 0
free_kicks_against             0
contested_possessions          0
uncontested_possessions        0
contested_marks                0
one_percenters                 0
total_score                    0
total_fantasy_points           0
avg_kicks                      0
avg_marks                      0
avg_handballs                  0
avg_disposals                  0
avg_goals                      0
avg_behinds                    0
avg_tackles                    0
avg_rebound_50s                0
avg_inside_50s                 0
avg_clearances                 0
avg_clangers                   0
avg_free_kicks_for             0
avg_free_kicks_against         0
avg_contested_possessions      0
avg_uncontested_possessions    0
avg_contested_marks            0
avg_one_percenters             0
avg_score                      0
avg_fantasy_points             0
dtype: int64

### 3. Duplicate Records Removed

In [108]:
# Duplicates before removal (from previous cell outputs)
print(f"Players duplicates before removal: 5")
print(f"Stats duplicates before removal: 10")
print(f"Merged duplicates before removal: 64")

# Duplicates after removal
print("\nDuplicates after removal:")
print(f"Players DataFrame duplicates: {players.duplicated().sum()}")
print(f"Stats DataFrame duplicates: {stats.duplicated().sum()}")
print(f"Merged DataFrame duplicates: {merged.duplicated().sum()}")

Players duplicates before removal: 5
Stats duplicates before removal: 10
Merged duplicates before removal: 64

Duplicates after removal:
Players DataFrame duplicates: 0
Stats DataFrame duplicates: 0
Merged DataFrame duplicates: 0

### 4. Unmatched Player IDs After Merging

In [109]:
print("Unmatched players from `players` DataFrame (not found in `stats`):")
print(unmatched_players.shape)

print("\nUnmatched stats entries from `stats` DataFrame (player_id not found in `players`):")
print(unmatched_stats.shape)

Unmatched players from `players` DataFrame (not found in `stats`):
(0, 14)

Unmatched stats entries from `stats` DataFrame (player_id not found in `players`):
(400, 44)